### ISSUE TITLE
Panic on suggest method

### ISSUE THREAD

**Issue by moxar** [elwinar/adeptus#16]
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.Character.Suggest(0xc8200e5228, 0x7, 0xc8200f2cf0, 0xc8200f2d20, 0xc8200f2d50, 0xc8200f2d80, 0xc8200f2db0, 0xc8200f2de0, 0xc8200f2e10, 0x1194, ...)
        /home/moxar/Dev/go/src/github.com/elwinar/adeptus/character.go:545 +0x24fc
main.main.func3(0xc8200982d0)
        /home/moxar/Dev/go/src/github.com/elwinar/adeptus/main.go:76 +0xb2
github.com/codegangsta/cli.Command.Run(0x5f1850, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6344c0, 0x39, 0x0, ...)
        /home/moxar/Dev/go/src/github.com/codegangsta/cli/command.go:127 +0x1052
github.com/codegangsta/cli.(*App).Run(0xc820096000, 0xc82000a2c0, 0x4, 0x4, 0x0, 0x0)
        /home/moxar/Dev/go/src/github.com/codegangsta/cli/app.go:159 +0xc2f
main.main()
        /home/moxar/Dev/go/src/github.com/elwinar/adeptus/main.go:81 +0x780
```

**Comment by moxar** [comment]
[sephiam.txt](https://github.com/elwinar/adeptus/files/40949/sephiam.txt)

[universe.txt](https://github.com/elwinar/adeptus/files/40950/universe.txt)
